#ifndef __BlueSideCallerPage__
#define __BlueSideCallerPage__

/**
@file
Subclass of CallerPage, which is generated by wxFormBuilder.
*/

#include "BlueSide.h"

//// end generated include

/** Implementing CallerPage */
class BlueSideCallerPage : public CallerPage {
 protected:
  // Handlers for CallerPage events.
  void makeCall(wxCommandEvent& event);
  void test(wxCommandEvent& event);
  void closeWindow(wxCloseEvent& event);

  public:
  /** Constructor */
  BlueSideCallerPage(wxWindow* parent);
  //// end generated class members
  void testCallAfter(std::string& msg);
};

#endif // __BlueSideCallerPage__
